apiVersion: v1
kind: Node
metadata:
  name: example-node
  version: 1.0.0
  description: "A sample node for the Sentiae marketplace"
  author: "Sentiae Team"
  license: MIT
  keywords:
    - example
    - sample
    - demo
    - data-processing
  repository: https://github.com/Sentiae/node-example
  homepage: https://github.com/Sentiae/node-example
  
spec:
  category: data-processing
  runtime: javascript
  entryPoint: index.js
  
  # Resource requirements
  resources:
    cpu: 100m
    memory: 256Mi
    
  # Input ports
  inputs:
    - name: data
      type: any
      description: "Input data to process"
      required: true
    - name: config
      type: object
      description: "Configuration options"
      required: false
      
  # Output ports
  outputs:
    - name: result
      type: any
      description: "Processed result"
    - name: metadata
      type: object
      description: "Processing metadata"
      
  # Dependencies
  dependencies:
    - name: lodash
      version: ^4.17.21
      type: runtime
    - name: axios
      version: ^1.6.0
      type: runtime
      
  # Configuration fields
  config:
    fields:
      - name: timeout
        type: number
        description: "Processing timeout in seconds"
        default: 30
        validation:
          min: 1
          max: 300
      - name: retries
        type: number
        description: "Number of retry attempts"
        default: 3
        validation:
          min: 0
          max: 10
      - name: debug
        type: boolean
        description: "Enable debug logging"
        default: false
        
  # UI configuration
  ui:
    icon: "📊"
    color: "#4CAF50"
    position:
      x: 100
      y: 100
    size:
      width: 200
      height: 150
      
  # Quality gates
  quality:
    testCoverage: 80.0
    securityScore: 95
    performanceScore: 85.0
    documentationScore: 90.0
    gates:
      - type: test_coverage
        threshold: 80.0
        required: true
      - type: security_score
        threshold: 85
        required: true
        
  # Documentation
  documentation:
    readme: |
      # Example Node
      
      This is an example node that demonstrates the basic structure
      and capabilities of a Sentiae marketplace node.
      
      ## Usage
      
      Connect input data to the `data` port and configure the node
      using the available configuration options.
      
      ## Features
      
      - Data processing with configurable timeout
      - Retry mechanism for failed operations
      - Debug logging support
      - Comprehensive error handling
      
    examples:
      - name: basic-usage
        description: "Basic data processing example"
        code: |
          // Example usage in a workflow
          {
            "timeout": 60,
            "retries": 5,
            "debug": true
          }
      - name: batch-processing
        description: "Batch processing example"
        code: |
          // Process multiple items
          {
            "timeout": 120,
            "retries": 3,
            "debug": false
          }
